import { defineConfig } from 'openapi-typescript';

export default defineConfig({
  // Input: Django backend schema URL
  input: process.env.API_SCHEMA_URL || 'http://localhost:8000/api/schema/',

  // Output: Generated TypeScript types
  output: './src/api/schema.d.ts',

  // Options
  auth: process.env.API_SCHEMA_TOKEN
    ? `Bearer ${process.env.API_SCHEMA_TOKEN}`
    : undefined,

  // Export type instead of interface for better inference
  exportType: true,

  // Add JSDoc comments from OpenAPI descriptions
  commentHeader: '/* Generated by openapi-typescript - DO NOT EDIT MANUALLY */',
});
